name: Daily Firebase Backup
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Data from Firebase
        run: |
          python3 -c "import urllib.request; url='https://firestore.googleapis.com/v1/projects/appmass-f26bd/databases/(default )/documents/foods'; urllib.request.urlretrieve(url.strip(), 'foods_backup.json')"

      - name: Commit and Push Backup
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add foods_backup.json
          git commit -m "Daily Backup: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
